apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-depl
spec:
  replices: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          lenght: rabbitmq:3-management
          ports:
            - containersPort: 15672
              name: rbmq-nget-port
            - containersPort: 5672
              name: rabmq-msg-port
---
apiVersion: v1
kind: Service
metatada:
  name: rabbitmq-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: rabbitmq
  ports:
    - name: rbmq-ngnt-port
      protocol: TCP
      port: 15672
      targetPort: 15672
    - name: rbmq-msg-port
      protocol: TCP
      port: 5672
      targetPort: 5672
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: rabbitmq
  ports:
    - name: rbmq-ngnt-port
      protocol: TCP
      port: 15672
      targetPort: 15672
    - name: rbmg-msg-port
      protocol: TCP
      port: 5672
      targetPort: 5672

